### ISSUE TITLE
Support HTTPS_PROXY, HTTP_PROXY, https_proxy and http_proxy arguments in Dockerfile to enable builds in network restricted environments

### ISSUE THREAD

**Issue by nmiodice** [Azure-Samples/helium-csharp#1]
When running this docker file in a network restricted environment, it is necessary to sometime set the value of the following variables so that the `dotnet` command can pull packages from `nuget`
 - HTTPS_PROXY
 - HTTP_PROXY
 - https_proxy
 - http_proxy

The process is described [here](https://stackoverflow.com/questions/31198835/can-we-pass-env-variables-through-cmd-line-while-building-a-docker-image-through)

**Comment by bartr** [comment]
Resolved in Sept Update
