### ISSUE TITLE
C# Docker environment for users that can't meet current Helium requirements.

### ISSUE THREAD

**Issue by AAkindele** [Azure-Samples/helium-csharp#146]
## Description

Give users a Docker environment for setting up Helium. Some users can't meet the current requirements, but they are able to use Docker Desktop.

- [x] A Dockerfile for helium csharp that can be used locally and in codespaces. This should include all the tools needed to step through the Helium setup.
- [x] Build the Dockerfile as part of ci/cd. Build on changes to the file, build and push to Docker Hub when merging to main.
- [x] Build and push the Dockerfile on a recurring schedule for package updates.
- [x] For codespaces, use the pre-built images for faster startup.

- References https://github.com/retaildevcrews/helium/issues/579

**Comment by lakshaykaushik** [comment]
Creating a Setup folder in root and pushing dockerfile to it. @AAkindele , is it Ok ?
Branch- https://github.com/retaildevcrews/helium-csharp/tree/heliumcsharpsetup

**Comment by AAkindele** [comment]
@lakshaykaushik Nice. Take a look at combining what you have with this existing file https://github.com/retaildevcrews/helium-csharp/blob/heliumcsharpsetup/docs/codespaces/Dockerfile. Also consider moving it to the `.devcontainer` directory, similar to the java repo.

**Comment by lakshaykaushik** [comment]
Done @AAkindele
